name: NUnit Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '6.0.x'

      - name: Dependency Install
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test > test_report.log

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'NUnit Test'
          path: 'test_report.log'
          reporter: 'dotnet-nunit'
          fail-on-error: 'false'
